import React, { useState } from "react";
import {
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { router } from "expo-router";
import { useAppUser } from "../../src/auth/clerk";
import {
  Button,
  Card,
  Heading,
  SectionLabel,
  theme,
} from "../../src/ui/primitives";
import { Dialog, Icon, SegmentedControl } from "../../src/ui/components";

type ExportFormat = "PDF" | "DOCX" | "Markdown";

export default function Settings() {
  const { name, email, isLoaded, isSignedIn, signOut } = useAppUser();

  const [exportFormat, setExportFormat] = useState<ExportFormat>("PDF");
  const [compactLists, setCompactLists] = useState<boolean>(false);
  const [manageOpen, setManageOpen] = useState<boolean>(false);

  const handleSignOut = async () => {
    await signOut();
    router.replace("/(auth)/login");
  };

  const displayName = name ?? "Draftoryn user";
  const displayEmail = email ?? "No email on file";

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.body}>
      <Heading level={2} style={styles.title}>
        Settings
      </Heading>

      {!isLoaded ? (
        <Card>
          <Text style={styles.muted}>Loading your account…</Text>
        </Card>
      ) : !isSignedIn ? (
        <Card>
          <Text style={styles.muted}>You are not signed in.</Text>
          <Button
            label="Sign in"
            variant="secondary"
            onPress={() => router.replace("/(auth)/login")}
          />
        </Card>
      ) : (
        <>
          <SectionLabel>Account</SectionLabel>
          <Card>
            <View style={styles.accountRow}>
              <View style={styles.avatar}>
                <Icon name="User" size={26} color={theme.accent} strokeWidth={1.5} />
              </View>
              <View style={styles.accountMeta}>
                <Text style={styles.accountName}>{displayName}</Text>
                <Text style={styles.accountEmail}>{displayEmail}</Text>
              </View>
            </View>
            <Button
              label="Manage account"
              variant="secondary"
              onPress={() => setManageOpen(true)}
              style={styles.actionButton}
            />
          </Card>

          <SectionLabel>Preferences</SectionLabel>
          <Card>
            <View style={styles.prefRow}>
              <View style={styles.prefText}>
                <Text style={styles.prefLabel}>Default export format</Text>
                <Text style={styles.prefHint}>
                  New documents start in this format when you export.
                </Text>
              </View>
            </View>
            <SegmentedControl<ExportFormat>
              options={[
                { value: "PDF", label: "PDF" },
                { value: "DOCX", label: "DOCX" },
                { value: "Markdown", label: "Markdown" },
              ]}
              value={exportFormat}
              onChange={setExportFormat}
            />
            <Pressable
              style={({ pressed }) => [
                styles.toggleRow,
                pressed && styles.togglePressed,
              ]}
              onPress={() => setCompactLists((v) => !v)}
            >
              <View style={styles.prefText}>
                <Text style={styles.prefLabel}>Compact lists</Text>
                <Text style={styles.prefHint}>
                  Use tighter spacing in document and draft lists.
                </Text>
              </View>
              <View style={[styles.switch, compactLists && styles.switchOn]}>
                <View style={[styles.knob, compactLists && styles.knobOn]} />
              </View>
            </Pressable>
          </Card>

          <SectionLabel>Documents</SectionLabel>
          <Card>
            <Text style={styles.bodyText}>
              Every document you create with Draftoryn carries a subtle
              Draftoryn watermark when exported, marking it as generated by
              this app. Exports use your chosen default format and keep the
              original layout intact.
            </Text>
          </Card>

          <SectionLabel>About</SectionLabel>
          <Card>
            <View style={styles.aboutRow}>
              <Text style={styles.aboutName}>Draftoryn</Text>
              <Text style={styles.aboutVersion}>Version 1.0.0</Text>
            </View>
            <Text style={styles.bodyText}>
              A calm writing studio that turns your briefs into polished,
              export-ready documents.
            </Text>
          </Card>

          <SectionLabel>Authentication</SectionLabel>
          <Card>
            <Text style={styles.bodyText}>
              You are signed in to Draftoryn. Signing out ends your session on
              this device.
            </Text>
            <Button
              label="Sign out"
              variant="danger"
              onPress={handleSignOut}
              style={styles.actionButton}
            />
          </Card>
        </>
      )}

      <Dialog
        open={manageOpen}
        onClose={() => setManageOpen(false)}
        title="Account managed by Clerk"
      >
        <Text style={styles.bodyText}>
          Your Draftoryn account is handled securely by Clerk, including your
          sign-in, email, and password. Account settings can be managed from
          the Clerk account area.
        </Text>
        <Button
          label="Close"
          variant="secondary"
          onPress={() => setManageOpen(false)}
          style={styles.actionButton}
        />
      </Dialog>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  body: {
    padding: 20,
    paddingTop: 32,
    paddingBottom: 48,
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
  },
  title: {
    marginBottom: 12,
  },
  muted: {
    fontFamily: theme.font.sans,
    color: theme.muted,
    fontSize: 15,
  },
  bodyText: {
    fontFamily: theme.font.sans,
    color: theme.text,
    fontSize: 15,
    lineHeight: 22,
  },
  accountRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: theme.surface2,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  accountMeta: {
    flex: 1,
  },
  accountName: {
    fontFamily: theme.font.serifSemi,
    color: theme.text,
    fontSize: 20,
    marginBottom: 2,
  },
  accountEmail: {
    fontFamily: theme.font.mono,
    color: theme.muted,
    fontSize: 13,
  },
  actionButton: {
    marginTop: 16,
  },
  prefRow: {
    marginBottom: 14,
  },
  prefText: {
    flex: 1,
  },
  prefLabel: {
    fontFamily: theme.font.sansMedium,
    color: theme.text,
    fontSize: 15,
    marginBottom: 2,
  },
  prefHint: {
    fontFamily: theme.font.sans,
    color: theme.muted,
    fontSize: 13,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 18,
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: theme.radiusSm,
  },
  togglePressed: {
    backgroundColor: theme.surface2,
  },
  switch: {
    width: 46,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.border,
    padding: 3,
    justifyContent: "center",
  },
  switchOn: {
    backgroundColor: theme.accent,
  },
  knob: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: theme.surface,
    alignSelf: "flex-start",
  },
  knobOn: {
    alignSelf: "flex-end",
  },
  aboutRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  aboutName: {
    fontFamily: theme.font.serifSemi,
    color: theme.text,
    fontSize: 20,
  },
  aboutVersion: {
    fontFamily: theme.font.mono,
    color: theme.muted,
    fontSize: 13,
  },
});
