import type {
  DocumentCategory,
  DocumentDefinition,
  ExportFormat,
  FieldDef,
  FieldType,
  SectionDef,
  SectionKind,
  SemanticConcept,
} from "../types";
import { CORE_EXPORT_FORMATS, USEFUL_EXPORT_FORMATS } from "../types";

// ---------------------------------------------------------------------------
// Field builders
// ---------------------------------------------------------------------------

interface FieldOpts {
  description?: string;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  default?: unknown;
  showIf?: FieldDef["showIf"];
  repeatable?: boolean;
  structured?: FieldDef[];
  mapsTo?: SemanticConcept;
  mapsKey?: string;
}

function field(type: FieldType, id: string, label: string, opts: FieldOpts = {}): FieldDef {
  return { type, id, label, ...opts };
}

const text = (id: string, label: string, o: FieldOpts = {}) => field("text", id, label, o);
const area = (id: string, label: string, o: FieldOpts = {}) => field("textarea", id, label, o);
const dateF = (id: string, label: string, o: FieldOpts = {}) => field("date", id, label, o);
const listF = (id: string, label: string, o: FieldOpts = {}) => field("list", id, label, { ...o, repeatable: true });
const mselect = (id: string, label: string, options: string[], o: FieldOpts = {}) =>
  field("multiselect", id, label, { ...o, options, repeatable: true });
const toggle = (id: string, label: string, o: FieldOpts = {}) => field("toggle", id, label, o);

function S(id: string, title: string, kind: SectionKind = "custom", opts: Partial<SectionDef> = {}): SectionDef {
  return { id, title, kind, ...opts };
}

const EXPORTS: ExportFormat[] = [...CORE_EXPORT_FORMATS, ...USEFUL_EXPORT_FORMATS];

function orgFields(prefix: "client" | "provider"): FieldDef[] {
  const cap = prefix === "client" ? "Client" : "Assessing / Provider";
  return [
    text(prefix + "Name", cap + " organization name", {
      required: prefix === "client",
      mapsTo: prefix,
      mapsKey: "name",
      placeholder: prefix === "client" ? "Acme Global Systems" : "Draftoryn Security Advisory",
    }),
    text(prefix + "ContactName", cap + " primary contact name", { mapsTo: prefix, mapsKey: "contactName" }),
    text(prefix + "ContactEmail", cap + " contact email", { mapsTo: prefix, mapsKey: "contactEmail" }),
    text(prefix + "Department", cap + " department / unit", { mapsTo: prefix, mapsKey: "department" }),
    text(prefix + "Phone", cap + " direct / emergency phone", { mapsTo: prefix, mapsKey: "phone" }),
  ];
}

function commonEngagementFields(): FieldDef[] {
  return [
    area("objective", "Engagement objectives & purpose", {
      mapsTo: "objective",
      description: "Core technical, business, and operational objectives of the activity.",
    }),
    listF("inScope", "In-scope targets / assets", {
      mapsTo: "scope",
      mapsKey: "inScope",
      description: "Hostnames, IP ranges, endpoints, cloud accounts, or applications included in the scope.",
    }),
    listF("outOfScope", "Explicitly out-of-scope targets", {
      mapsTo: "scope",
      mapsKey: "outOfScope",
      description: "Excluded environments, third-party services, production databases, or physical boundaries.",
    }),
    dateF("startDate", "Execution start date", { mapsTo: "schedule", mapsKey: "start" }),
    dateF("endDate", "Execution end date", { mapsTo: "schedule", mapsKey: "end" }),
    listF("windows", "Permitted testing windows", { mapsTo: "schedule", mapsKey: "windows" }),
    text("authorizedBy", "Authorizing sponsor / signatory", { mapsTo: "authorization", mapsKey: "authorizedBy" }),
    text("authReference", "Authorization reference / contract ID", { mapsTo: "authorization", mapsKey: "reference" }),
    dateF("authDate", "Authorization date", { mapsTo: "authorization", mapsKey: "date" }),
    listF("constraints", "Prohibited actions / safety constraints", {
      mapsTo: "constraints",
      description: "Prohibited actions (e.g. DoS, credential modification, production data destruction).",
    }),
    listF("methodology", "Methodology & standards", { mapsTo: "methodology" }),
    listF("evidence", "Evidence collection requirements", { mapsTo: "evidence" }),
    listF("deliverables", "Deliverables & reports", { mapsTo: "reporting", mapsKey: "deliverables" }),
    text("reportAudience", "Deliverable audience", { mapsTo: "reporting", mapsKey: "audience" }),
    listF("assumptions", "Operational assumptions & prerequisites", { mapsTo: "assumptions" }),
  ];
}

export const CATEGORIES: DocumentCategory[] = [
  "offensive_security",
  "incident_response_dfir",
  "threat_intelligence",
  "security_architecture_engineering",
  "risk_governance",
  "resilience",
];

export const CATEGORY_LABELS: Record<DocumentCategory, string> = {
  offensive_security: "Offensive Security",
  incident_response_dfir: "Incident Response / DFIR",
  threat_intelligence: "Threat Intelligence",
  security_architecture_engineering: "Security Architecture / Engineering",
  risk_governance: "Risk / Governance",
  resilience: "Resilience",
};

export const DOCUMENT_DEFINITIONS: DocumentDefinition[] = [
  // =========================================================================
  // 1. OFFENSIVE SECURITY
  // =========================================================================
  {
    id: "roe",
    slug: "rules-of-engagement",
    name: "Rules of Engagement (RoE)",
    category: "offensive_security",
    description: "Operational framework defining boundaries, safety constraints, escalation protocols, and testing hours for offensive activities.",
    audience: "Client security operations, test team leaders, and incident responders.",
    purpose: "Ensure offensive testing executes safely without uncoordinated disruptions or operational hazard.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      text("emergencyStopContact", "Emergency stop contact / hotline"),
      listF("permittedTools", "Permitted testing toolsets & frameworks"),
      listF("prohibitedTechniques", "Prohibited exploits & techniques"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("authority_consent", "Authority and Consent", "authorization"),
      S("operational_boundaries", "Operational Boundaries", "scope"),
      S("permitted_windows", "Permitted Testing Windows", "schedule"),
      S("critical_protections", "Critical Asset Protections", "constraints"),
      S("communications", "Communication and Escalation", "communications"),
      S("emergency_stop", "Deconfliction and Emergency Stop", "escalation"),
      S("evidence_handling", "Evidence Handling", "evidence"),
      S("deliverables_reporting", "Deliverables and Reporting", "reporting"),
      S("signoff", "Acceptance and Sign-off", "signoff"),
    ],
  },
  {
    id: "pentest_agreement",
    slug: "penetration-testing-agreement-authorization",
    name: "Penetration Testing Agreement / Authorization",
    category: "offensive_security",
    description: "Binding legal and technical authorization specifying testing permissions, mutual responsibilities, safe harbor, and liability.",
    audience: "Executive leadership, legal counsel, and security testing providers.",
    purpose: "Grant explicit legal consent to perform penetration testing with well-defined constraints.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      text("legalJurisdiction", "Governing jurisdiction / law"),
      area("confidentialityTerms", "Confidentiality terms & non-disclosure clauses"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("parties", "Parties and Responsibilities", "parties"),
      S("overview", "Engagement Overview", "purpose_bg"),
      S("scope", "Scope of Authorization", "scope"),
      S("authorization", "Authorization and Consent", "authorization"),
      S("testing_boundaries", "Testing Boundaries", "testing_boundaries"),
      S("confidentiality", "Confidentiality and Safe Harbor", "confidentiality"),
      S("evidence", "Data and Evidence Handling", "evidence"),
      S("reporting", "Reporting and Deliverables", "reporting"),
      S("emergency_escalation", "Incident / Emergency Escalation", "escalation"),
      S("schedule", "Schedule and Maintenance Windows", "schedule"),
      S("liability_terms", "Indemnification and Limitation of Liability", "assumptions"),
      S("signoff", "Acceptance and Sign-off", "signoff"),
    ],
  },
  {
    id: "pentest_plan",
    slug: "penetration-testing-plan",
    name: "Penetration Testing Plan",
    category: "offensive_security",
    description: "Technical roadmap describing execution phases, target discovery, attack modeling, toolsets, and logistics.",
    audience: "Security assessors, system administrators, and engagement managers.",
    purpose: "Establish clear technical steps, phasing, and requirements before initiating penetration testing.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      listF("testingPhases", "Testing phases (e.g. Recon, Scanning, Exploitation, Post-Exploit)"),
      listF("requiredAccess", "Required credentials, VPN access, and IP allowlists"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("engagement_summary", "Engagement Summary", "exec_summary"),
      S("technical_objectives", "Technical Objectives", "objectives"),
      S("target_architecture", "Target Environment Architecture", "intro"),
      S("scoped_targets", "Scoped Targets and IP Ranges", "in_scope"),
      S("phases_methodology", "Testing Phases and Methodology", "methodology"),
      S("tooling_techniques", "Tooling and Attack Techniques", "activities"),
      S("resource_logistics", "Resource and Logistics Plan", "schedule"),
      S("risk_mitigation", "Risk Mitigation and Contingencies", "constraints"),
      S("reporting_schedule", "Reporting and Debrief Schedule", "reporting"),
      S("signoff", "Approval and Sign-off", "signoff"),
    ],
  },
  {
    id: "pentest_report",
    slug: "penetration-testing-report",
    name: "Penetration Testing Report",
    category: "offensive_security",
    description: "Full technical assessment report detailing verified security findings, exploit narratives, severity ratings, and remediation.",
    audience: "CISO, engineering managers, devops leads, and remediation engineers.",
    purpose: "Provide clear risk context and actionable remediation directives based on observed exploitability.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      listF("criticalFindings", "Key vulnerabilities identified"),
      text("overallRiskRating", "Overall engagement risk rating (e.g. High / Critical)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("scope_methodology", "Scope and Methodology", "scope"),
      S("attack_narrative", "Attack Narrative and Attack Paths", "activities"),
      S("risk_breakdown", "Key Findings and Risk Breakdown", "findings"),
      S("technical_findings", "Detailed Technical Vulnerabilities", "findings"),
      S("strategic_recommendations", "Strategic Recommendations", "recommendations"),
      S("tactical_remediation", "Tactical Remediation Steps", "recommendations"),
      S("testing_limitations", "Testing Limitations", "assumptions"),
      S("retest_guidance", "Retest Guidance", "reporting"),
      S("appendix_evidence", "Appendix: Supporting Evidence", "evidence"),
    ],
  },
  {
    id: "redteam_report",
    slug: "red-team-assessment-report",
    name: "Red Team Assessment Report",
    category: "offensive_security",
    description: "Multi-domain adversary emulation report evaluating enterprise detection, response times, lateral movement, and defense depth.",
    audience: "Chief Information Security Officer, Security Operations Center leadership, and executive board.",
    purpose: "Evaluate the effectiveness of defensive teams, detection tooling, and resilience against real-world attack tactics.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      text("emulatedThreatActor", "Adversary group emulated (e.g. APT29 / Scattered Spider)"),
      listF("campaignFlags", "Objectives / Flags captured during emulation"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("threat_actor_emulated", "Threat Actor Emulated", "intro"),
      S("scenarios_objectives", "Scenarios and Campaign Objectives", "objectives"),
      S("campaign_narrative", "Chronological Campaign Narrative", "activities"),
      S("soc_detection_analysis", "Blue Team Detection and Evasion Analysis", "findings"),
      S("lateral_movement", "Compromised Assets and Lateral Movement", "findings"),
      S("mitre_mapping", "MITRE ATT&CK Mapping", "methodology"),
      S("critical_exposures", "Critical Exposure Areas", "findings"),
      S("defense_recommendations", "Defense Recommendations", "recommendations"),
      S("appendix_iocs", "Appendix: Indicators of Compromise (IoCs)", "evidence"),
    ],
  },
  {
    id: "va_report",
    slug: "vulnerability-assessment-report",
    name: "Vulnerability Assessment Report",
    category: "offensive_security",
    description: "Systematic identification, categorization, and CVSS severity scoring of vulnerabilities across scoped network and cloud infrastructure.",
    audience: "IT operations, security engineers, and compliance officers.",
    purpose: "Provide a complete inventory of known software flaws, misconfigurations, and outdated services.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      text("scanningEngine", "Scanning tool or platform utilized"),
      listF("scannedSubnets", "Scanned CIDR blocks, hostnames, or repositories"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("scope_coverage", "Asset Scope and Coverage", "scope"),
      S("scan_methodology", "Scan and Assessment Methodology", "methodology"),
      S("severity_summary", "Vulnerability Summary by Severity", "findings"),
      S("high_critical_findings", "High and Critical Findings", "findings"),
      S("network_findings", "Infrastructure and Network Findings", "findings"),
      S("configuration_weaknesses", "Configuration Weaknesses", "findings"),
      S("remediation_roadmap", "Prioritized Remediation Roadmap", "recommendations"),
      S("patch_verification", "Patch Verification Procedures", "reporting"),
      S("appendix_statistics", "Appendix: Full Scan Statistics", "evidence"),
    ],
  },
  {
    id: "sec_assessment_report",
    slug: "security-assessment-report",
    name: "Security Assessment Report",
    category: "offensive_security",
    description: "Comprehensive review of organizational security controls, identity policies, cloud hygiene, and defense capabilities.",
    audience: "Security leadership, internal audit, and technology management.",
    purpose: "Benchmark security posture against industry standards and deliver prioritized strategic improvements.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      ...commonEngagementFields(),
      text("assessmentFramework", "Framework evaluated (e.g. NIST CSF / CIS Critical Controls / ISO 27001)"),
      text("maturityLevel", "Current assessed maturity level"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("scope_objectives", "Assessment Scope and Objectives", "scope"),
      S("framework_evaluated", "Control Framework Evaluated", "methodology"),
      S("maturity_scorecard", "Posture Scorecard and Maturity Ratings", "findings"),
      S("technical_findings", "Technical Controls Findings", "findings"),
      S("policy_findings", "Administrative and Policy Controls", "findings"),
      S("identity_governance", "Identity and Access Governance", "findings"),
      S("strategic_roadmap", "Strategic Security Roadmap", "recommendations"),
      S("quick_wins", "Operational Quick Wins", "recommendations"),
      S("signoff", "Conclusion and Sign-off", "signoff"),
    ],
  },

  // =========================================================================
  // 2. INCIDENT RESPONSE / DFIR
  // =========================================================================
  {
    id: "ir_plan",
    slug: "incident-response-plan",
    name: "Incident Response Plan",
    category: "incident_response_dfir",
    description: "Enterprise operating plan establishing triage workflows, severity matrices, team rosters, and communication procedures.",
    audience: "CISO, incident commander, security operations center, and legal teams.",
    purpose: "Standardize incident handling from detection to containment and recovery, minimizing business impact.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("planOwner", "Incident response program owner / coordinator"),
      listF("escalationHotlines", "Emergency escalation hotlines & war room channels"),
      listF("severityThresholds", "Severity tier definitions (P1 Critical through P4 Low)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("purpose_scope", "Purpose and Scope", "purpose_bg"),
      S("severity_matrix", "Incident Classification and Severity Matrix", "definitions"),
      S("cirt_roles", "Incident Response Team (CIRT) Roles", "parties"),
      S("phase_preparation", "Phase 1: Preparation and Monitoring", "activities"),
      S("phase_detection", "Phase 2: Detection and Analysis", "activities"),
      S("phase_containment", "Phase 3: Containment and Eradication", "activities"),
      S("phase_recovery", "Phase 4: Recovery and Post-Incident", "activities"),
      S("legal_regulatory", "Legal and Regulatory Notification", "escalation"),
      S("plan_maintenance", "Testing and Plan Maintenance", "signoff"),
    ],
  },
  {
    id: "ir_playbook",
    slug: "incident-response-playbook",
    name: "Incident Response Playbook",
    category: "incident_response_dfir",
    description: "Scenario-specific operational checklist for containment, eradication, and forensics (e.g. Ransomware, Business Email Compromise).",
    audience: "SOC tier 2/3 analysts, incident handlers, and system administrators.",
    purpose: "Provide deterministic technical step-by-step guidance when a specific threat type triggers.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("threatScenario", "Threat scenario (e.g. Ransomware Outbreak / Cloud Account Takeover)"),
      listF("triggerConditions", "Detection indicators triggering playbook execution"),
      listF("isolationProcedures", "Emergency network and identity isolation steps"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("playbook_overview", "Playbook Overview and Trigger Conditions", "intro"),
      S("triage_verification", "Initial Triage and Verification", "activities"),
      S("immediate_containment", "Immediate Containment Actions", "activities"),
      S("forensic_preservation", "Forensic Preservation Steps", "evidence"),
      S("eradication_remediation", "Eradication and Remediation", "activities"),
      S("system_recovery", "System Recovery and Validation", "schedule"),
      S("stakeholder_comms", "Stakeholder Communications", "communications"),
      S("closure_checklist", "Incident Closure Checklist", "signoff"),
    ],
  },
  {
    id: "incident_report",
    slug: "incident-report",
    name: "Incident Report",
    category: "incident_response_dfir",
    description: "Comprehensive record documenting a specific cyber security incident, technical root cause, impact, and response timeline.",
    audience: "Executive management, regulators, insurers, and technical leads.",
    purpose: "Provide a factual, verified account of an incident's scope, timeline, and mitigation actions.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("incidentNumber", "Incident tracking ID / ticket reference"),
      dateF("incidentDate", "Incident detection date"),
      text("incidentType", "Incident classification (e.g. Data Exfiltration / Ransomware)"),
      listF("affectedSystems", "Impacted systems, endpoints, or data stores"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("incident_overview", "Incident Overview and Severity", "intro"),
      S("root_cause", "Root Cause Analysis", "findings"),
      S("timeline", "Chronological Incident Timeline", "schedule"),
      S("impact_assessment", "Systems and Data Impacted", "findings"),
      S("containment_actions", "Containment and Remediation Measures", "activities"),
      S("evidence_preserved", "Evidence Preserved", "evidence"),
      S("regulatory_disclosures", "Regulatory and Legal Disclosures", "escalation"),
      S("case_closure", "Sign-off and Case Closure", "signoff"),
    ],
  },
  {
    id: "forensics_report",
    slug: "digital-forensics-report",
    name: "Digital Forensics Report",
    category: "incident_response_dfir",
    description: "Expert investigative findings detailing chain of custody, filesystem analysis, memory dumps, and anti-forensic indicators.",
    audience: "Legal counsel, internal investigators, law enforcement, and security leadership.",
    purpose: "Deliver scientifically defensible digital evidence analysis and factual reconstruction of unauthorized activity.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("caseNumber", "Investigation case number"),
      listF("evidenceItems", "Physical and digital evidence items seized / analyzed"),
      text("leadExaminer", "Lead forensic examiner"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("investigation_overview", "Investigation Overview", "intro"),
      S("chain_of_custody", "Evidence Chain of Custody", "evidence"),
      S("acquisition_methodology", "Forensic Acquisition and Imaging Methodology", "methodology"),
      S("disk_analysis", "Disk and File System Analysis", "findings"),
      S("memory_analysis", "Memory and Process Analysis", "findings"),
      S("network_artifacts", "Network and Log Artifacts", "findings"),
      S("forensic_timeline", "Timeline of Forensic Events", "schedule"),
      S("investigative_opinion", "Conclusions and Investigative Opinion", "recommendations"),
      S("appendix_hashes", "Appendix: Tool Validation and Hashes", "evidence"),
    ],
  },
  {
    id: "malware_report",
    slug: "malware-analysis-report",
    name: "Malware Analysis Report",
    category: "incident_response_dfir",
    description: "Deep technical analysis of malicious binaries, unpack routines, C2 beaconing protocols, persistence mechanisms, and IOCs.",
    audience: "Threat intelligence analysts, reverse engineers, and SOC detection engineers.",
    purpose: "Deconstruct malicious code capabilities to produce threat intelligence and actionable detection signatures.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("sampleFileName", "Analyzed sample filename"),
      text("sha256Hash", "SHA-256 cryptographic hash"),
      text("malwareFamily", "Identified malware family / classification"),
      listF("c2Addresses", "Identified Command & Control (C2) IP addresses and domains"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("sample_metadata", "File Sample Metadata and Hashes", "intro"),
      S("static_analysis", "Static Analysis Findings", "findings"),
      S("dynamic_analysis", "Dynamic and Sandbox Execution Analysis", "findings"),
      S("code_disassembly", "Code Disassembly and Capabilities", "findings"),
      S("c2_network", "Network Communications and C2 Protocol", "findings"),
      S("persistence_evasion", "Persistence and Defense Evasion", "findings"),
      S("iocs", "Indicators of Compromise (IoCs)", "evidence"),
      S("detection_signatures", "Detection Signatures (YARA / Suricata)", "recommendations"),
    ],
  },
  {
    id: "lessons_learned_report",
    slug: "post-incident-lessons-learned-report",
    name: "Post-Incident / Lessons Learned Report",
    category: "incident_response_dfir",
    description: "Structured post-mortem evaluating incident root causes, detection delays, communication bottlenecks, and control upgrades.",
    audience: "Executive leadership, IT operations, security architecture, and risk committees.",
    purpose: "Transform real-world security incidents into concrete architectural improvements and organizational resilience.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("incidentReference", "Resolved incident reference ID"),
      text("durationHours", "Total incident duration from detection to recovery (hours)"),
      listF("identifiedGaps", "Core gaps identified during incident response"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("retrospective_summary", "Incident Retrospective Summary", "intro"),
      S("lifecycle_evaluation", "IR Lifecycle Evaluation", "methodology"),
      S("successes", "What Worked Well", "findings"),
      S("identified_gaps", "Gaps and Pain Points Identified", "findings"),
      S("technical_causes", "Technical Root Causes", "findings"),
      S("action_plan", "Corrective Action Plan and Owners", "recommendations"),
      S("preventive_controls", "Preventive Control Recommendations", "recommendations"),
      S("review_signoff", "Post-Incident Review Sign-off", "signoff"),
    ],
  },

  // =========================================================================
  // 3. THREAT INTELLIGENCE
  // =========================================================================
  {
    id: "threat_intel_report",
    slug: "threat-intelligence-report",
    name: "Threat Intelligence Report",
    category: "threat_intelligence",
    description: "Actionable intelligence brief synthesizing adversary tactics, exploitation trends, emerging vulnerabilities, and telemetry.",
    audience: "Chief Information Security Officer, security engineering, and intelligence consumers.",
    purpose: "Deliver timely intelligence on active threats and prioritize defensive countermeasures before exploitation occurs.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("threatTopic", "Primary threat topic / campaign focus"),
      text("confidenceLevel", "Confidence level (High / Moderate / Low)"),
      listF("targetedSectors", "Targeted industry verticals & sectors"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("landscape_overview", "Threat Landscape Overview", "intro"),
      S("adversary_profile", "Adversary Profile and Motivation", "intro"),
      S("targeted_sectors", "Targeted Sectors and Geography", "scope"),
      S("ttps", "Tactics, Techniques, and Procedures (TTPs)", "methodology"),
      S("observables", "Technical Indicators and Observables", "evidence"),
      S("diamond_model", "Diamond Model Analysis", "findings"),
      S("defensive_guidance", "Defensive Recommendations", "recommendations"),
      S("dissemination", "Intelligence Confidence and Dissemination", "reporting"),
    ],
  },
  {
    id: "threat_actor_profile",
    slug: "threat-actor-profile",
    name: "Threat Actor Profile",
    category: "threat_intelligence",
    description: "In-depth intelligence dossier detailing threat actor motivations, operational infrastructure, attack patterns, and tooling.",
    audience: "Threat hunters, SOC analysts, and cyber defense architects.",
    purpose: "Document an adversary group's signature tradecraft to enable proactive hunting and detection engineering.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("actorName", "Threat actor designation (e.g. Midnight Blizzard / Volt Typhoon)"),
      listF("knownAliases", "Known aliases and tracking handles"),
      text("originCountry", "Suspected country of origin / attribution"),
      listF("primaryObjectives", "Actor motivations and strategic objectives"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("actor_overview", "Threat Actor Overview", "intro"),
      S("aliases_attribution", "Aliases and Attribution", "intro"),
      S("motivations", "Motivations and Objectives", "objectives"),
      S("victimology", "Victimology and Sector Targeting", "scope"),
      S("tooling_exploits", "Known Tooling and Exploits", "findings"),
      S("infrastructure_c2", "Infrastructure and C2 Patterns", "findings"),
      S("mitre_matrix", "MITRE ATT&CK Matrix Mapping", "methodology"),
      S("campaign_timeline", "Historical Campaign Timeline", "schedule"),
      S("detection_strategies", "Detection Strategies and Signatures", "recommendations"),
    ],
  },
  {
    id: "threat_assessment_report",
    slug: "threat-assessment-report",
    name: "Threat Assessment Report",
    category: "threat_intelligence",
    description: "Evaluative assessment quantifying threat actor interest, capability, and likely impact against specific organizational assets.",
    audience: "Risk committees, CISO, and executive stakeholders.",
    purpose: "Correlate external threat intelligence with internal vulnerability posture to evaluate plausible threat scenarios.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      listF("criticalAssets", "Organizational critical assets assessed"),
      listF("relevantThreatGroups", "Threat groups relevant to industry/region"),
      text("threatTimeHorizon", "Assessment time horizon (e.g. Next 12 Months)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("scope_assets", "Assessment Scope and Assets at Risk", "scope"),
      S("threat_environment", "Threat Environment and Relevant Actor Groups", "intro"),
      S("scenario_modeling", "Threat Scenario Modeling", "findings"),
      S("capability_scoring", "Likelihood and Threat Capability Scoring", "findings"),
      S("vulnerability_alignment", "Vulnerability and Exposure Alignment", "findings"),
      S("prioritization_matrix", "Risk Prioritization Matrix", "findings"),
      S("countermeasures", "Countermeasure Recommendations", "recommendations"),
      S("review_schedule", "Review Schedule and Sign-off", "signoff"),
    ],
  },
  {
    id: "campaign_analysis_report",
    slug: "campaign-analysis-report",
    name: "Campaign Analysis Report",
    category: "threat_intelligence",
    description: "Comprehensive breakdown of a coordinated malicious campaign spanning phishing lures, exploit delivery, and command-and-control.",
    audience: "Intelligence analysts, defense teams, and incident responders.",
    purpose: "Deliver situational awareness on active campaign telemetry, victim targeting, and actionable indicators.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("campaignName", "Campaign name or identifier"),
      dateF("firstObserved", "Date first observed"),
      listF("deliveryMechanisms", "Observed delivery vectors (e.g. Malicious PDF, Watering Hole)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("campaign_summary", "Campaign Summary and Naming", "intro"),
      S("access_vectors", "Initial Access and Phishing Vectors", "activities"),
      S("delivery_mechanisms", "Exploit and Delivery Mechanisms", "findings"),
      S("c2_infrastructure", "C2 Infrastructure Analysis", "findings"),
      S("target_demographics", "Target Demographics and Sector Impact", "scope"),
      S("attribution_correlation", "Correlation with Known Threat Groups", "findings"),
      S("campaign_milestones", "Campaign Timeline and Milestones", "schedule"),
      S("tactical_iocs", "Tactical Indicators of Compromise", "evidence"),
      S("hunting_queries", "Hunting and Detection Queries", "recommendations"),
    ],
  },

  // =========================================================================
  // 4. SECURITY ARCHITECTURE / ENGINEERING
  // =========================================================================
  {
    id: "threat_model",
    slug: "threat-model",
    name: "Threat Model",
    category: "security_architecture_engineering",
    description: "Structured architectural analysis applying STRIDE/PASTA to identify trust boundaries, entry points, and mitigations.",
    audience: "Software architects, lead engineers, and application security specialists.",
    purpose: "Proactively identify and mitigate design-level vulnerabilities prior to engineering implementation.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("systemName", "Target application or system name"),
      listF("trustBoundaries", "Trust boundaries (e.g. Internet vs VPC, User vs Kernel)"),
      listF("entryPoints", "System entry points, APIs, and exposed interfaces"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("system_overview", "System Overview and Architectural Context", "intro"),
      S("trust_boundaries", "Data Flow and Trust Boundaries", "scope"),
      S("entry_points", "Asset and Entry Point Inventory", "scope"),
      S("stride_analysis", "STRIDE Threat Analysis", "findings"),
      S("attack_paths", "Threat Scenarios and Attack Paths", "activities"),
      S("risk_scoring", "Risk Scoring and Exposure Assessment", "findings"),
      S("required_controls", "Required Security Controls", "recommendations"),
      S("residual_risks", "Residual Risk Acceptance", "assumptions"),
      S("verification", "Verification Criteria and Sign-off", "signoff"),
    ],
  },
  {
    id: "sec_arch_doc",
    slug: "security-architecture-document",
    name: "Security Architecture Document",
    category: "security_architecture_engineering",
    description: "Enterprise engineering specification establishing security zones, cryptographic standards, IAM controls, and SIEM telemetry.",
    audience: "Enterprise architects, engineering directors, and cloud infrastructure teams.",
    purpose: "Provide an authoritative reference for secure system design, boundaries, and control implementation.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("systemScope", "Architectural scope / platform boundary"),
      listF("securityZones", "Defined network and compute security zones"),
      listF("complianceStandards", "Applicable standards (e.g. FedRAMP / PCI-DSS / SOC 2)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("arch_scope", "Architectural Scope and Objectives", "scope"),
      S("topology_zones", "Network Topology and Security Zones", "intro"),
      S("iam_architecture", "Identity and Access Management (IAM) Architecture", "findings"),
      S("data_crypto", "Data Protection and Cryptographic Standards", "findings"),
      S("boundary_protection", "Threat Defenses and Boundary Protection", "findings"),
      S("telemetry_siem", "Logging, Telemetry, and SIEM Integration", "findings"),
      S("failover_design", "High Availability and Failover Design", "schedule"),
      S("compliance_matrix", "Compliance Control Cross-Reference", "methodology"),
      S("signoff", "Architecture Approval and Sign-off", "signoff"),
    ],
  },
  {
    id: "sec_design_review",
    slug: "security-design-review",
    name: "Security Design Review",
    category: "security_architecture_engineering",
    description: "Rigorous technical assessment of a planned feature, service, or integration against secure design principles and least privilege.",
    audience: "Product managers, engineering leads, and application security reviewers.",
    purpose: "Certify that new technical designs adhere to security requirements before writing code.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("featureName", "Feature or service under review"),
      text("leadDesigner", "Lead system designer / engineering owner"),
      listF("dataClassification", "Data types processed (e.g. PII, Credentials, Financial)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("feature_summary", "Feature / System Summary", "intro"),
      S("review_scope", "Review Scope and Design Artifacts", "scope"),
      S("abuse_cases", "Threat Analysis and Abuse Cases", "findings"),
      S("auth_review", "Authentication and Authorization Design Review", "findings"),
      S("storage_transit", "Data Storage and Transit Controls", "findings"),
      S("dependency_risk", "Third-Party Dependency Risk", "findings"),
      S("design_deficiencies", "Security Design Deficiencies", "findings"),
      S("required_remediations", "Required Remediations", "recommendations"),
      S("signoff", "Engineering Approval and Sign-off", "signoff"),
    ],
  },
  {
    id: "cloud_sec_assessment",
    slug: "cloud-security-assessment",
    name: "Cloud Security Assessment",
    category: "security_architecture_engineering",
    description: "Comprehensive evaluation of cloud account governance, IAM entitlements, container runtime, and storage bucket security.",
    audience: "Cloud security architects, DevOps managers, and compliance leads.",
    purpose: "Identify cloud misconfigurations, privilege over-allocation, and public exposures across multi-cloud environments.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("cloudProvider", "Cloud provider (AWS / Azure / GCP)"),
      listF("accountIds", "Scoped cloud account IDs / subscriptions / projects"),
      listF("complianceBaselines", "Baselines evaluated (e.g. CIS AWS Benchmark, Well-Architected)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("scoped_accounts", "Scoped Cloud Accounts and Environments", "scope"),
      S("benchmark_baseline", "Cloud Security Baseline and Benchmark", "methodology"),
      S("iam_entitlements", "Identity, Entitlements, and Access (CIEM)", "findings"),
      S("network_vpcs", "Network Security and Virtual Private Clouds", "findings"),
      S("data_storage_posture", "Data Storage and Encryption Posture", "findings"),
      S("workload_security", "Container and Serverless Workload Security", "findings"),
      S("logging_monitoring", "Logging, GuardDuty, and Monitoring", "findings"),
      S("remediation_plan", "Prioritized Cloud Remediation Plan", "recommendations"),
    ],
  },
  {
    id: "app_sec_assessment",
    slug: "application-security-assessment",
    name: "Application Security Assessment",
    category: "security_architecture_engineering",
    description: "In-depth technical evaluation of web, mobile, or microservice applications covering OWASP Top 10 vulnerabilities and business logic.",
    audience: "Application security engineers, software development managers, and product owners.",
    purpose: "Uncover and remediate security vulnerabilities in application logic, APIs, and authentication flows.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("applicationName", "Target application title"),
      text("appUrl", "Application primary URL or staging endpoint"),
      listF("apiEndpoints", "Scoped API endpoints and routes"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("app_scope", "Application Scope and API Endpoints", "scope"),
      S("assessment_methodology", "Testing Methodology (DAST / SAST / Manual)", "methodology"),
      S("auth_session", "Authentication and Session Security", "findings"),
      S("access_control", "Access Control and Authorization Flaws", "findings"),
      S("input_validation", "Input Validation and Injection Flaws", "findings"),
      S("business_logic", "Business Logic and Data Exposure", "findings"),
      S("findings_narrative", "Detailed Findings and PoC Narratives", "findings"),
      S("remediation_guidance", "Remediation Guidance and Fix Recommendations", "recommendations"),
    ],
  },

  // =========================================================================
  // 5. RISK / GOVERNANCE
  // =========================================================================
  {
    id: "cyber_risk_assessment",
    slug: "cybersecurity-risk-assessment",
    name: "Cybersecurity Risk Assessment",
    category: "risk_governance",
    description: "Enterprise risk assessment evaluating threat capabilities, asset criticality, control effectiveness, and residual risk appetite.",
    audience: "Enterprise risk management, board audit committee, and executive leadership.",
    purpose: "Quantify cyber risk in business context and establish informed risk treatment priorities.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("riskAssessor", "Lead risk assessor / governance officer"),
      text("riskAppetiteStatement", "Organizational risk appetite statement"),
      listF("criticalBusinessServices", "Critical business services assessed"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("risk_methodology", "Risk Assessment Methodology and Appetite", "methodology"),
      S("scoped_assets", "Scoped Business Assets and Services", "scope"),
      S("threat_vulnerability", "Threat and Vulnerability Identification", "findings"),
      S("inherent_risk", "Inherent Risk Ratings", "findings"),
      S("control_effectiveness", "Existing Control Effectiveness", "findings"),
      S("residual_profile", "Residual Risk Profile and Heatmap", "findings"),
      S("treatment_options", "Risk Treatment Recommendations", "recommendations"),
      S("signoff", "Management Sign-off and Risk Acceptance", "signoff"),
    ],
  },
  {
    id: "risk_register",
    slug: "risk-register",
    name: "Risk Register",
    category: "risk_governance",
    description: "Living enterprise ledger documenting identified security risks, likelihood/impact scoring, assigned owners, and remediation milestones.",
    audience: "Security governance leads, IT managers, and compliance auditors.",
    purpose: "Maintain a continuous, auditable record of all operational and cybersecurity risks.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("registerVersion", "Risk register review version / quarter"),
      listF("topRisks", "Primary high-priority risk entries"),
      text("reviewCycle", "Mandatory review cadence (e.g. Monthly / Quarterly)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("register_purpose", "Risk Register Scope and Purpose", "intro"),
      S("scoring_matrix", "Risk Scoring Methodology (5x5 Matrix)", "methodology"),
      S("high_critical_risks", "Critical and High Risk Entries", "findings"),
      S("moderate_low_risks", "Moderate and Low Risk Entries", "findings"),
      S("ownership_matrix", "Risk Owner and Accountability Matrix", "parties"),
      S("mitigation_milestones", "Mitigation Progress and Milestones", "schedule"),
      S("audit_history", "Audit and Review History", "reporting"),
      S("governance_signoff", "Risk Governance Sign-off", "signoff"),
    ],
  },
  {
    id: "third_party_sec_assessment",
    slug: "third-party-security-assessment",
    name: "Third-Party Security Assessment",
    category: "risk_governance",
    description: "Vendor risk assessment evaluating supplier security controls, data privacy compliance, SOC 2 reports, and supply chain vulnerability.",
    audience: "Vendor management, procurement, legal, and information security teams.",
    purpose: "Evaluate and mitigate cybersecurity risks introduced by external partners and SaaS vendors.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("vendorName", "Vendor or supplier organization name"),
      text("serviceProvided", "Service or software provided"),
      text("dataClassificationHandled", "Classification of client data accessed by vendor"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("vendor_profile", "Vendor Profile and Service Description", "intro"),
      S("data_classification", "Data Sensitivity and Access Classification", "scope"),
      S("audit_certifications", "Compliance and Audit Certification Review", "methodology"),
      S("controls_evaluation", "Technical and Operational Controls Evaluation", "findings"),
      S("supply_chain_risks", "Supply Chain and Fourth-Party Risks", "findings"),
      S("residual_risks", "Identified Deficiencies and Residual Risks", "findings"),
      S("approval_decision", "Vendor Approval Recommendation", "recommendations"),
      S("monitoring_schedule", "Ongoing Monitoring Schedule and Sign-off", "signoff"),
    ],
  },
  {
    id: "sec_exception_waiver",
    slug: "security-exception-risk-acceptance",
    name: "Security Exception / Risk Acceptance",
    category: "risk_governance",
    description: "Formal exception waiver documenting business justification, compensating controls, residual risk, and sunset date for policy deviations.",
    audience: "Security leadership, enterprise risk officers, and technical system owners.",
    purpose: "Authorize a controlled, temporary deviation from security standards with executive visibility and compensating protections.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("policyWaived", "Security policy or standard being waived"),
      area("businessJustification", "Business justification & technical limitation"),
      dateF("expirationDate", "Exception expiration / sunset date"),
      listF("compensatingControls", "Compensating security controls implemented"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exception_summary", "Exception Summary and Scope", "intro"),
      S("policy_waived", "Policy or Standard Being Waived", "scope"),
      S("business_justification", "Business Justification and Rationale", "objectives"),
      S("risk_analysis", "Technical Risk Analysis and Threat Potential", "findings"),
      S("compensating_controls", "Compensating Security Controls", "recommendations"),
      S("sunset_plan", "Expiration Date and Sunset Plan", "schedule"),
      S("monitoring_conditions", "Conditions and Monitoring Requirements", "constraints"),
      S("executive_signoff", "Executive Approval and Signatures", "signoff"),
    ],
  },

  // =========================================================================
  // 6. RESILIENCE
  // =========================================================================
  {
    id: "bia_report",
    slug: "business-impact-analysis",
    name: "Business Impact Analysis (BIA)",
    category: "resilience",
    description: "Operational analysis quantifying the financial and business consequences of system downtime, establishing RTO and RPO benchmarks.",
    audience: "Chief Operating Officer, continuity coordinators, and business line owners.",
    purpose: "Identify critical business processes and prioritize disaster recovery resources according to operational urgency.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      listF("criticalFunctions", "Critical business functions evaluated"),
      text("targetRTO", "Maximum acceptable Recovery Time Objective (RTO)"),
      text("targetRPO", "Maximum acceptable Recovery Point Objective (RPO)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("bia_scope", "BIA Scope and Methodology", "scope"),
      S("function_inventory", "Critical Business Function Inventory", "intro"),
      S("disruption_impact", "Operational and Financial Disruption Impact", "findings"),
      S("rto_rpo_metrics", "Recovery Time Objectives (RTO) and Recovery Point Objectives (RPO)", "schedule"),
      S("system_dependencies", "System and Vendor Dependencies", "findings"),
      S("vital_records", "Vital Records and Asset Requirements", "evidence"),
      S("resilience_recommendations", "Strategic Resilience Recommendations", "recommendations"),
      S("signoff", "Sign-off and Executive Endorsement", "signoff"),
    ],
  },
  {
    id: "bcp_plan",
    slug: "business-continuity-plan",
    name: "Business Continuity Plan (BCP)",
    category: "resilience",
    description: "Enterprise playbook for maintaining mission-critical operations, remote workforce agility, and executive leadership during major crises.",
    audience: "Business continuity team, executive leadership, and departmental leaders.",
    purpose: "Ensure the organization survives prolonged facility, human, or infrastructure outages with minimal disruption.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("continuityDirector", "Business continuity coordinator / director"),
      listF("alternateWorkLocations", "Designated alternate facilities and remote protocols"),
      listF("activationTriggers", "Disaster activation criteria and thresholds"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("scope_objectives", "Plan Scope and Objectives", "scope"),
      S("command_structure", "Continuity Command Structure and Roles", "parties"),
      S("activation_criteria", "Activation Criteria and Mobilization", "activities"),
      S("alternate_workforce", "Alternate Site and Remote Workforce Strategy", "activities"),
      S("recovery_procedures", "Critical Business Function Recovery Procedures", "activities"),
      S("communications", "Inter-Team Communications and Coordination", "communications"),
      S("vital_records_access", "Vital Records Access and Data Continuity", "evidence"),
      S("maintenance_schedule", "Testing, Training, and Maintenance Schedule", "schedule"),
    ],
  },
  {
    id: "drp_plan",
    slug: "disaster-recovery-plan",
    name: "Disaster Recovery Plan (DRP)",
    category: "resilience",
    description: "Technical disaster recovery roadmap detailing infrastructure failover, cloud redundancy, database recovery, and network routing.",
    audience: "IT infrastructure leads, database administrators, and disaster recovery coordinators.",
    purpose: "Restore technology platforms, compute services, and storage following catastrophic datacenter or cloud outages.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("drLead", "Disaster recovery technical lead"),
      text("primaryDataCenter", "Primary datacenter or cloud region"),
      text("secondaryDataCenter", "Secondary failover datacenter or region"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("exec_summary", "Executive Summary", "exec_summary"),
      S("dr_scope", "Disaster Recovery Scope and Objectives", "scope"),
      S("dr_team_roles", "DR Team Roles and Emergency Contacts", "parties"),
      S("declaration_procedures", "Disaster Declaration Procedures", "activities"),
      S("infrastructure_failover", "Primary Data Center and Cloud Failover", "activities"),
      S("database_restoration", "Database and Storage Backup Restoration", "activities"),
      S("network_routing", "Network Routing and DNS Switching", "activities"),
      S("system_verification", "System Verification and Validation", "findings"),
      S("fallback_operations", "Post-Recovery Fallback to Normal Operations", "signoff"),
    ],
  },
  {
    id: "cyber_recovery_plan",
    slug: "cyber-recovery-plan",
    name: "Cyber Recovery Plan",
    category: "resilience",
    description: "Specialized playbook for rebuilding enterprise infrastructure, domain controllers, and databases following destructive cyberattacks.",
    audience: "Enterprise architects, identity engineers, CISOs, and cyber recovery task forces.",
    purpose: "Provide deterministic recovery procedures when primary and secondary environments have been corrupted by ransomware or wiper malware.",
    exportFormats: EXPORTS,
    fields: [
      ...orgFields("client"),
      ...orgFields("provider"),
      text("airGappedVaultLocation", "Air-gapped / immutable backup vault location"),
      listF("isolatedCleanRooms", "Isolated clean-room network environments"),
      listF("criticalIdentitySystems", "Core identity systems (e.g. Active Directory Forest, IdP)"),
    ],
    sections: [
      S("doc_control", "Document Control", "doc_control"),
      S("plan_overview", "Plan Overview and Purpose", "intro"),
      S("cyber_vs_dr", "Cyber Recovery vs. Traditional DR", "definitions"),
      S("recovery_roles", "Cyber Recovery Team and Roles", "parties"),
      S("immutable_isolation", "Immutable Clean Backup Isolation", "evidence"),
      S("identity_forest_recovery", "Active Directory and Identity Forest Recovery", "activities"),
      S("workload_reintroduction", "Staged Workload Re-introduction and Scans", "activities"),
      S("network_containment", "Network Containment and Egress Filtering", "constraints"),
      S("production_certification", "Production Re-certification", "findings"),
      S("post_recovery_review", "Post-Recovery Forensics and Review", "signoff"),
    ],
  },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

const BY_ID = new Map<string, DocumentDefinition>(
  DOCUMENT_DEFINITIONS.map((d) => [d.id, d]),
);
const BY_SLUG = new Map<string, DocumentDefinition>(
  DOCUMENT_DEFINITIONS.map((d) => [d.slug, d]),
);

export function getDefinition(idOrSlug: string): DocumentDefinition | undefined {
  return BY_ID.get(idOrSlug) ?? BY_SLUG.get(idOrSlug);
}

export function getDefinitionById(id: string): DocumentDefinition | undefined {
  return BY_ID.get(id);
}

export function getDefinitionBySlug(slug: string): DocumentDefinition | undefined {
  return BY_SLUG.get(slug);
}

export function listDefinitions(): DocumentDefinition[] {
  return DOCUMENT_DEFINITIONS;
}

export function definitionsByCategory(category: DocumentCategory): DocumentDefinition[] {
  return DOCUMENT_DEFINITIONS.filter((d) => d.category === category);
}