import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  Footer,
  type IRunOptions,
} from "docx";
import type { ContentBlock, GeneratedDocument, Section } from "../types";

const border = { style: BorderStyle.SINGLE, size: 4, color: "E8E4DF" };
const cellBorders = { top: border, bottom: border, left: border, right: border };

function runs(text: string, opts: IRunOptions = {}): TextRun[] {
  return [new TextRun({ text, ...opts })];
}

function blockToDocx(b: ContentBlock): (Paragraph | Table)[] {
  switch (b.type) {
    case "heading":
      return [new Paragraph({ text: b.text ?? "", heading: b.level === 1 ? HeadingLevel.TITLE : b.level === 3 ? HeadingLevel.HEADING_3 : HeadingLevel.HEADING_2 })];
    case "paragraph":
      return [new Paragraph({ children: runs(b.text ?? "") })];
    case "list":
      return (b.items ?? []).map((it) => new Paragraph({ bullet: { level: 0 }, children: runs(it) }));
    case "table": {
      const t = b.table;
      if (!t) return [];
      const header = new TableRow({
        tableHeader: true,
        children: t.headers.map((h) => new TableCell({ borders: cellBorders, children: [new Paragraph({ children: runs(h, { bold: true }) })] })),
      });
      const rows = t.rows.map(
        (r) =>
          new TableRow({
            children: r.map((c) => new TableCell({ borders: cellBorders, children: [new Paragraph({ children: runs(c) })] })),
          }),
      );
      return [new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [header, ...rows] })];
    }
    case "callout":
      return [new Paragraph({ children: runs(`${String(b.tone ?? "NOTE").toUpperCase()}: ${b.text ?? ""}`, { italics: true, color: "B8860B" }) })];
    case "divider":
      return [new Paragraph({ children: [new TextRun({ text: "―".repeat(20), color: "D0D5DD" })] })];
  }
}

function sectionToDocx(s: Section): (Paragraph | Table)[] {
  const head = [new Paragraph({ text: s.title, heading: HeadingLevel.HEADING_2 })];
  const body = s.blocks.flatMap(blockToDocx);
  return [...head, ...body];
}

export async function toDocx(doc: GeneratedDocument): Promise<Uint8Array> {
  const children: (Paragraph | Table)[] = [
    new Paragraph({ text: doc.title, heading: HeadingLevel.TITLE }),
  ];
  const meta = Object.entries(doc.metadata).filter(([, v]) => v).map(([k, v]) => `${k}: ${v}`).join("   |   ");
  if (meta) children.push(new Paragraph({ children: runs(meta, { size: 18, color: "667085" }) }));
  for (const s of doc.sections.filter((x) => !x.hidden)) children.push(...sectionToDocx(s));

  const gen = doc.generator;
  const watermarkText = gen
    ? `Generated by Draftoryn ${gen.version} · ${gen.generatedAt}`
    : "Generated with Draftoryn";
  const footer = [
    new Paragraph({ children: runs(watermarkText, { size: 16, color: "B8860B" }) }),
    new Paragraph({ children: runs("Draftoryn — specialist cybersecurity document generation. Not for distribution without authorization.", { size: 14, color: "6B6B6B" }) }),
  ];

  const document = new Document({
    sections: [{ children, footers: { default: new Footer({ children: footer }) } }],
  });

  if (typeof Blob !== "undefined" && typeof (Packer as unknown as { toBlob?: unknown }).toBlob === "function") {
    const blob = await (Packer as unknown as { toBlob: (d: Document) => Promise<Blob> }).toBlob(document);
    const buf = await blob.arrayBuffer();
    return new Uint8Array(buf);
  }
  const buffer = await Packer.toBuffer(document);
  return new Uint8Array(buffer);
}
