import type { ContentBlock, GeneratedDocument, Section } from "../types";
import { visibleSections } from "./markdown";

const TONE_CLASS: Record<string, string> = {
  info: "callout-info",
  warning: "callout-warning",
  missing: "callout-missing",
  assumption: "callout-assumption",
  neutral: "callout-info",
};

function blockToHtml(b: ContentBlock, i: number): string {
  const id = `b${i}`;
  switch (b.type) {
    case "heading": {
      const level = Math.min(Math.max(Math.floor(b.level ?? 2), 1), 6);
      return `<h${level}>${escape(b.text ?? "")}</h${level}>`;
    }
    case "paragraph":
      return `<p>${escape(b.text ?? "")}</p>`;
    case "list":
      return `<ul>${(b.items ?? []).map((it) => `<li>${escape(it)}</li>`).join("")}</ul>`;
    case "table": {
      const t = b.table;
      if (!t) return "";
      const head = `<thead><tr>${t.headers.map((h) => `<th>${escape(h)}</th>`).join("")}</tr></thead>`;
      const rows = `<tbody>${t.rows
        .map((r) => `<tr>${r.map((c) => `<td>${escape(c)}</td>`).join("")}</tr>`)
        .join("")}</tbody>`;
      return `<table>${head}${rows}</table>`;
    }
    case "callout":
      return `<div class="callout ${TONE_CLASS[b.tone ?? "info"] ?? "callout-info"}"><strong>${String(b.tone ?? "NOTE").toUpperCase().replace(/[^A-Z]/g, "") || "NOTE"}</strong> ${escape(b.text ?? "")}</div>`;
    case "divider":
      return `<hr/>`;
  }
}

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(s: string): string {
  return escape(s).replace(/[^a-zA-Z0-9 _-]/g, "");
}

function sectionToHtml(s: Section): string {
  const blocks = s.blocks.map((b, i) => blockToHtml(b, i)).join("\n");
  return `<section class="doc-section" data-kind="${escapeAttr(s.kind)}">\n<h2>${escape(s.title)}</h2>\n${blocks}\n</section>`;
}

const CSS = `
:root { --ink:#090A0C; --text:#101216; --muted:#555A64; --line:#E2E4E8; --accent:#2F6BFF; --surface:#F5F3EE; --mono:'IBM Plex Mono', Menlo, Consolas, monospace; }
body { font-family: 'Inter Tight', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: var(--text); max-width: 860px; margin: 48px auto; padding: 0 32px 80px; line-height: 1.6; background: #FFFFFF; }
h1 { font-size: 26px; font-weight: 700; letter-spacing: -0.02em; border-bottom: 2px solid var(--accent); padding-bottom: 12px; margin-bottom: 16px; color: var(--ink); }
h2 { font-size: 18px; font-weight: 600; letter-spacing: -0.01em; margin-top: 36px; margin-bottom: 14px; padding-bottom: 6px; border-bottom: 1px solid var(--line); color: var(--ink); }
table { border-collapse: collapse; width: 100%; margin: 16px 0 20px; }
th, td { border: 1px solid var(--line); padding: 10px 12px; text-align: left; font-size: 13px; }
th { background: #F8F9FA; font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); font-weight: 600; }
p { font-size: 14px; margin: 8px 0 12px; color: #22252A; }
ul { margin: 8px 0 16px 24px; padding: 0; }
li { margin-bottom: 6px; font-size: 14px; color: #22252A; }
hr { border: 0; border-top: 1px solid var(--line); margin: 24px 0; }
.callout { border-left: 3px solid var(--accent); background: #F4F7FF; padding: 12px 16px; margin: 16px 0; border-radius: 4px; font-size: 13px; line-height: 1.5; }
.callout-missing { border-color: #D94A4A; background: #FFF5F5; }
.callout-warning { border-color: #D99A24; background: #FFFBF0; }
.callout-assumption { border-color: #2F6BFF; background: #F4F7FF; }
.callout-info { border-color: var(--accent); }
.doc-section { margin-bottom: 28px; }
.meta { color: var(--muted); font-size: 12px; font-family: var(--mono); margin-bottom: 24px; letter-spacing: 0.02em; }
.watermark { position: fixed; right: 20px; bottom: 16px; font-family: var(--mono); font-size: 10px; letter-spacing: 0.12em; color: var(--muted); opacity: 0.6; text-transform: uppercase; }
.draftoryn-footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid var(--line); color: var(--muted); font-size: 11px; font-family: var(--mono); }
`;

export function toHtml(doc: GeneratedDocument): string {
  const meta = Object.entries(doc.metadata)
    .filter(([, v]) => v)
    .map(([k, v]) => `<span>${escape(k)}: ${escape(v)}</span>`)
    .join(" &middot; ");
  const sections = visibleSections(doc).map(sectionToHtml).join("\n");
  const gen = doc.generator;
  const footer = gen
    ? `<div class="draftoryn-footer">Generated by ${escape(gen.product)} ${escape(gen.version)} &middot; ${escape(gen.generatedAt)} &middot; Draftoryn — specialist cybersecurity document generation</div>`
    : `<div class="draftoryn-footer">Generated with Draftoryn</div>`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${escape(doc.title)}</title>
<style>${CSS}</style>
</head>
<body>
<h1>${escape(doc.title)}</h1>
<p class="meta">${meta}</p>
${sections}
${footer}
<div class="watermark">Draftoryn</div>
</body>
</html>`;
}
