import type { ContentBlock, GeneratedDocument, Section } from "../types";

export function visibleSections(doc: GeneratedDocument): Section[] {
  return doc.sections.filter((s) => !s.hidden);
}

function blockToMarkdown(b: ContentBlock): string {
  switch (b.type) {
    case "heading":
      return `${"#".repeat(Math.min(b.level ?? 2, 6))} ${b.text ?? ""}`;
    case "paragraph":
      return b.text ?? "";
    case "list":
      return (b.items ?? []).map((i) => `- ${i}`).join("\n");
    case "table": {
      const t = b.table;
      if (!t) return "";
      const head = `| ${t.headers.join(" | ")} |`;
      const sep = `| ${t.headers.map(() => "---").join(" | ")} |`;
      const rows = t.rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
      return [head, sep, rows].join("\n");
    }
    case "callout":
      return `> **${b.tone?.toUpperCase() ?? "NOTE"}:** ${b.text ?? ""}`;
    case "divider":
      return "---";
  }
}

export function sectionToMarkdown(s: Section): string {
  const lines: string[] = [];
  if (s.title) lines.push(`## ${s.title}`);
  for (const b of s.blocks) {
    const md = blockToMarkdown(b);
    if (md) lines.push(md);
  }
  return lines.join("\n\n");
}

export function toMarkdown(doc: GeneratedDocument): string {
  const parts: string[] = [];
  parts.push(`# ${doc.title}`);
  const meta = Object.entries(doc.metadata).filter(([, v]) => v).map(([k, v]) => `- ${k}: ${v}`);
  if (meta.length) parts.push(meta.join("\n"));
  for (const s of visibleSections(doc)) {
    const md = sectionToMarkdown(s);
    if (md) parts.push(md);
  }
  const gen = doc.generator;
  const watermark = gen
    ? `\n---\n\n*Generated by ${gen.product} ${gen.version} · ${gen.generatedAt}*` +
      `\n\nThis document was produced with Draftoryn, a specialist cybersecurity document-generation platform.`
    : `\n\n*Generated with Draftoryn*`;
  return parts.join("\n\n") + "\n" + watermark + "\n";
}
